// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAV0iw6y0AZJXY9iRkbqWH1Nr-hqDqGiM4',
    appId: '1:583518390952:web:3af1e81051dc707af0109d',
    messagingSenderId: '583518390952',
    projectId: 'analyticss-250eb',
    authDomain: 'analyticss-250eb.firebaseapp.com',
    storageBucket: 'analyticss-250eb.appspot.com',
    measurementId: 'G-140YD9ZRX6',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCalKBZJw5Vr_aox5pBRzBTeGsNwhWspq8',
    appId: '1:583518390952:ios:6811a4e3f41eadd6f0109d',
    messagingSenderId: '583518390952',
    projectId: 'analyticss-250eb',
    storageBucket: 'analyticss-250eb.appspot.com',
    iosBundleId: 'com.example.analyticsTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCalKBZJw5Vr_aox5pBRzBTeGsNwhWspq8',
    appId: '1:583518390952:ios:6811a4e3f41eadd6f0109d',
    messagingSenderId: '583518390952',
    projectId: 'analyticss-250eb',
    storageBucket: 'analyticss-250eb.appspot.com',
    iosBundleId: 'com.example.analyticsTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAV0iw6y0AZJXY9iRkbqWH1Nr-hqDqGiM4',
    appId: '1:583518390952:web:3b0b2080aff643c4f0109d',
    messagingSenderId: '583518390952',
    projectId: 'analyticss-250eb',
    authDomain: 'analyticss-250eb.firebaseapp.com',
    storageBucket: 'analyticss-250eb.appspot.com',
    measurementId: 'G-PEXMMCNRWW',
  );
}
